Implement modules and stages
Otus-DevOps-2023-01/andreynovikov_infra pull request #6
Opened 2023-04-05 21:24 UTC by andreynovikov

# Выполнено ДЗ №7

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- конфигурация разбита на несколько файлов                                                                                                                                                                                  
- конфигурация выделена в отдельные модули                                                                                                                                                                                  
- созданы копии конфигурации для stage и production                                                                                                                                                                         
- отформатированы все конфигурационные файлы 

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-04-06 08:11 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Вам нужно подмержить в эту ветку изменения из дз с пакером и снова запустить тест
ДЗ возвращаю на доработку

2023-04-14 16:52 UTC, andreynovikov commented
А у меня тут уже есть смерженная ветка packer

2023-04-15 15:16 UTC, mrgreyves commented
Значит нужно подмержить изменения из пакера в эту ветку
Свертесь с результатами тестов

2023-05-24 17:55 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув )
ЗЫ - с дз все ок =)

2023-07-02 18:31 UTC, merged